### 4.4 배열의 파일 입출력

#### 4.4.1 배열을 바이너리 형식으로 디스크에 저장하기

np.save와 np.load를 사용해보자

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.save('./data/some_array', arr)  # 확장자는 .npy로 저장된다.

In [8]:
np.load('./data/some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez('./data/array_archive.npz', a=arr, b=arr)  # 압축하여 저장하는 방법

In [12]:
arch = np.load('./data/array_archive.npz')
arch

In [13]:
print(arch['a'])
print(arch['b'])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


#### 텍스트 파일 불러오기와 저장하기

보통은 판다스로 불러오지만  
np.loadtxt나 np.getfromtxt를 이용해 NumPy 배열로 직접 데이터를 불러오는 게 유용할 때도 있다.

In [37]:
# 텍스트 파일 만들기
np.set_printoptions(precision=8)
arr = np.random.randn(6, 4)
import pandas as pd
dataframe = pd.DataFrame(arr)
dataframe.to_csv('./data/array_ex.txt', header=False, index=False)

0         1         2         3
0  0.275103 -1.183067 -0.278992 -0.933298
1 -0.438085 -0.881695  0.698922  0.681943
2  0.916456 -0.522822  0.178933 -0.187381
3 -1.241121  0.054615 -1.199155  0.013361
4  1.153276  0.227325 -2.055139 -0.597644
5  0.631758  1.980567  0.019772 -0.727807

In [39]:
load_arr = np.loadtxt('./data/array_ex.txt', delimiter=',')
load_arr

array([[ 0.27510327, -1.18306683, -0.27899218, -0.93329777],
       [-0.43808478, -0.88169467,  0.69892204,  0.68194326],
       [ 0.91645551, -0.52282211,  0.17893322, -0.18738073],
       [-1.24112078,  0.05461505, -1.19915516,  0.01336072],
       [ 1.15327575,  0.22732482, -2.05513863, -0.59764446],
       [ 0.63175775,  1.98056712,  0.01977166, -0.72780726]])