### 4.5 선형대수

배열을 잘 다루려면 선형대수는 중요하다.

행렬의 곱에 대해서 알아보자

In [3]:
import numpy as np

In [23]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


x * y 를 해보자 에러가 난다. 행렬곱을 하고싶으면 dot 함수를 쓴다.  
x.dot(y)

In [27]:
# x * y
# 3by2 와 2by3을 곱할 수 없다. 행렬곱이 지원이 되지않는다.
# operands could not be broadcast together with shapes (2,3) (3,2)

In [28]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

2차원 배열과 곱셈이 가능한 크기의 1차원 배열 간 행렬 곱셈의 결과는 1차원이다.

In [29]:
np.dot(x, np.ones(3))

array([ 6., 15.])

numpy.linalg는 행렬의 분할과 역행렬, 행렬식 같은 것을 포함한다.  
MATLAB, R같은 언어에서 사용하는 표준 포트란 라이브러리인 BLAS, LAPACK, Intel MKL을 사용해서 구현되었다.  

In [32]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
X

array([[ 0.26203289,  1.88249428, -0.66642381, -0.81586954, -0.95984161],
       [-0.23888869, -1.81940367, -1.48506606, -0.35628267,  1.38584206],
       [-2.38620275,  0.33147114, -0.44450934,  0.53371307,  0.09717905],
       [ 1.00126898,  1.79401223,  0.58151203, -1.09183891,  0.23346473],
       [ 0.52549106,  0.77684302, -1.53271951, -0.11389564, -0.86398869]])

In [34]:
mat = X.T.dot(X)  # 전치행렬
mat

array([[ 7.09837302e+00,  2.34146590e+00,  1.01764949e+00,
        -2.55529593e+00, -1.03471831e+00],
       [ 2.34146590e+00,  1.07858525e+01,  1.15261085e+00,
        -2.75798866e+00, -4.54843542e+00],
       [ 1.01764949e+00,  1.15261085e+00,  5.53451580e+00,
         3.75230358e-01, -1.58783663e-03],
       [-2.55529593e+00, -2.75798866e+00,  3.75230358e-01,
         2.28251451e+00,  1.84718414e-01],
       [-1.03471831e+00, -4.54843542e+00, -1.58783663e-03,
         1.84718414e-01,  3.65228014e+00]])

In [36]:
inv(mat)  # 정사각 행렬의 역행렬

array([[ 0.8242886 ,  0.94816896, -0.48712951,  2.04248037,  1.31083444],
       [ 0.94816896,  1.62806192, -0.71431475,  2.9724873 ,  2.14551312],
       [-0.48712951, -0.71431475,  0.51472641, -1.41573045, -0.95576665],
       [ 2.04248037,  2.9724873 , -1.41573045,  6.22824844,  3.96487611],
       [ 1.31083444,  2.14551312, -0.95576665,  3.96487611,  3.11618184]])

In [37]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.21961943e-16,  2.06546096e-16,
         2.00860947e-15,  4.35787423e-16],
       [ 2.14147763e-15,  1.00000000e+00, -1.96780178e-15,
         3.02237239e-15,  3.47372086e-15],
       [ 4.33149734e-16,  1.40369654e-16,  1.00000000e+00,
         8.00835909e-17,  9.39640349e-17],
       [-1.22976964e-15,  6.39518965e-16,  1.49607217e-16,
         1.00000000e+00,  1.94846690e-16],
       [-7.22475756e-16,  1.19130586e-15,  5.59803377e-16,
        -1.16964487e-15,  1.00000000e+00]])

In [38]:
q, r = qr(mat)
r

array([[ -8.03150993,  -6.82338503,  -1.81752502,   3.7649158 ,
          2.77003084],
       [  0.        , -10.24118018,  -0.75816392,   1.63494451,
          4.85334357],
       [  0.        ,   0.        ,  -5.40902745,  -0.96801045,
         -0.45727233],
       [  0.        ,   0.        ,   0.        ,  -1.31763088,
          1.91427654],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.17496578]])

자주 사용되는 numpy.linalg 함수

- numpy.diag: 정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환하거나 1차원 배열을 대각선 원소로 하고, 나머지는 0으로 채운 단위 행렬을 반환한다.
- numpy.dot: 행렬 곱셈
- numpy.trace: 행렬의 대각선 원소의 합을 계산
- numpy.linalg.det: 행렬식을 계산
- numpy.linalg.eig: 정사각 행렬의 고유 값과 고유벡터를 계산
- numpy.linalg.inv: 정사각 행렬의 역행렬을 계산
- numpy.linalg.pinv: 행렬의 무어-펜로즈 유사역원 역행렬을 구함
- numpy.linalg.qr: QR 분해를 계산
- numpy.linalg.svd: 특이값 분해(SVD)를 계산
- numpy.linalg.solve: A가 정사각 행렬일 때, Ax = b 를 만족하는 x를 구함
- numpy.linalg.lstsq: y=xb를 만족하는 최소제곱해를 구함