## 4. NumPy 기본

NumPy란 Numerical Python의 줄임말이다.

고성능 과학계산 컴퓨팅과 데이터 분석에 필요한 기본 패키지다.

넘파이의 장점

- 빠르고 메모리를 효율적으로 사용, 벡터 산술연산과 세련된 브로드캐스팅 기능 제공
- 데이터 배열에 대한 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선형대수, 난수 발생기, 푸리에 변환 기능
- C, C++, 포트란으로 쓰여진 코드를 통합하는 도구

넘파이 기능

데이터 분석 애플리케이션에서 중요하게 사용되는 기능들

- 벡터 배열상에서 데이터 개조, 정제, 부분 집합, 필터링, 변형 다른 종류 연산의 빠른 수행
- 정렬, 유일 원소 찾기, 집합애ㅕㄴ산 같은 일반적인 배열 처리 알고리즘
- 통계의 효과적인 표현과 데이터의 수집/요약
- 다른 종류의 데이터 묶음을 병합하고 엮기 위한 데이터 정렬과 데이터 간의 관계 조작
- 반복문 대신 사용할 수 있는 조건절을 표현할 수 있는 배열 표현
- 데이터 그룹 전체에 적용할 수 있는 수집, 변형, 함수 적용 같은 데이터 처리

### 4.1 NumPy ndarray: 다차원 배열 객체

In [8]:
import numpy as np

In [9]:
data = np.random.randn(2, 3)  # 2 by 3 행렬생성, 값은 -1~1까지
data

array([[-0.10963984,  1.21535033, -0.39403577],
       [ 1.13515928, -0.50604193, -1.46138898]])

넘파이는 백터연산을 지원한다.

In [10]:
data * 100

array([[ -10.96398443,  121.53503297,  -39.40357684],
       [ 113.51592753,  -50.60419254, -146.13889788]])

In [11]:
data + data

array([[-0.21927969,  2.43070066, -0.78807154],
       [ 2.27031855, -1.01208385, -2.92277796]])

ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다.

shape는 각 차원의 크기를 알려주고

dtype은 배열에 저장된 자료형을 알려준다.

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

#### 4.1.1 ndarray 생성

배열, NumPy 배열, ndarray는 ndarry 객체를 이르는 말이다.

첫번째 배열을 생성하는 방법

array 함수를 이용하여 만든다. 시퀀스 자료형을 넘겨주면 된다.

In [17]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2 = [(1, 2, 3, 4), [4, 5, 6, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

명시적으로 지정하지 않는 한 np.array는 생성될 때 적절한 자료형을 추정한다.

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

두번째 새로운 배열을 만드는 방법

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
np.empty((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

세번째 배열을 만드는 방법

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### 정리

표준 배열 생성 함수 만들기

NumPy는 산술연산에 초점이 맞춰져 있기 때문에 float64(부동소수점)가 될 것이다.

- np.array(tuple type): ndarray로 변환, 자료형을 추론하여 저장, 자료 깊은 복사
- np.asarry(sequence type): ndarray로 변환, 입력 데이터가 메모리에 있을경우 복사가 되지 않음
- np.aranage(int type): ndarray로 반환, range함수와 유사
- np.ones(tuple type): 주어진 dtype과 주어진 모양을 가는 배열 생성 후, 1로 초기화
- np.ones_likes(sequence type): 주어진 배열과 동일한 모양과 dtype을 가지는 배열을 새로 생성 후, 1로 초기화
- np.zeros(), np.zeros_likes(): ones와 동일, ones_likes와 동일, 단 값은 0으로 초기화
- np.empty(), np.empty_likes(): ones와 동일, ones_lies와 동일, 단 값은 1로 초기화(책에는 빈 값으로 초기화)
- np.eye(int type), np.identity(int type): int값 만큼의 N by N 전치행렬 생성

In [46]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones_like([(4, 5, 6), (1, 2, 3)])  # 2 by 3 이 들어갔으므로 2 by 3 배열 완성

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
dir(np.array(3))

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

#### 4.1.2 ndarray의 자료형

In [57]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [58]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [59]:
arr1.dtype

dtype('float64')

In [60]:
arr2.dtype

dtype('int32')

##### NumPy의 dtype 들
- int8, uint8: 부호가 있는 8bit(8byte) 정수형, 부호가 없는(unsigned) 8q비트 정수형
- int16, int32, int64, uint8, uint16, uint32, uint64
- float16, float32, float64, float128: 반정밀도 ,단정밀도, 배정밀도, 확장 정밀도
- complex64, complex128, complex256: 각각 2개의 32, 64, 128bit 부동소수점형을 가지는 복소수
- bool: True, False
- object: 파이썬 객체형
- string_: 고정 길이 문자열형(각 글자는 1byte), 길이가 10인 문자열의 dtype은 S10이 된다.
- unicode_: 고정 길이 유니코드형(플랫폼에 따라 글자별 byte수는 다르다), string_형과 같은 형식을 쓴다. ex) U10

NumPy의 dtype은 외울 필요는 없다.

단 주로 대용량 데이터가 메모리나 디스크에 저장되는 방식을 제어해야 할 때 알아두면 좋다.

ndarray의 astype 메소드를 사용해서 배열의 dtype을 다른 형으로 명시적 변경 가능하다.

In [62]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [68]:
float_arr = np.array([3.7, 4, -1.2, -0.5])
float_arr.dtype

dtype('float64')

In [69]:
float_arr.astype(np.int32)  # 실수를 정수로 바꾸면 소수점이 버려진다.

array([ 3,  4, -1,  0])

In [74]:
numeric_strings = np.array(['1.25', '-9.5', '4.3'])
numeric_strings

array(['1.25', '-9.5', '4.3'], dtype='<U4')

In [76]:
new_strings = numeric_strings.astype(float)
new_strings

array([ 1.25, -9.5 ,  4.3 ])

In [77]:
new_strings.dtype

dtype('float64')

In [81]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
calibers = np.array([.22, .270, .357, .380], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 ])

In [87]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
int_array.astype(calibers.dtype).dtype

dtype('float64')

dtype으로 사용할 수 있는 축약 코드도 있다. u4는 uint32와 동일하다.

In [125]:
empty_uint32 = np.empty((3, 2), dtype='u4')
empty_uint32

array([[         0, 1072955392],
       [         0, 3223519232],
       [ 858993459, 1074869043]], dtype=uint32)

In [126]:
arr = np.array([22323, 3], dtype='unicode')
arr

array(['22323', '3'], dtype='<U5')

### 4.1.3 배열과스칼라 간의 연산

배열은 반복문을 작성하지 않고 데이터를 일괄처리할 수 있다.

벡터화 연산 지원이라고 한다.

In [95]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [96]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [97]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [99]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

#### 4.1.4 색인과 슬라이싱 기초

NumPy 배열 색인은 파이썬의 리스트와 유사동작한다.

In [100]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr[5]

5

In [102]:
arr[5:8]

array([5, 6, 7])

In [103]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [104]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [106]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [107]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

리스트와의 중요한 차이점은 배열 조각(slice)은 배열의 뷰라는 점이다.

즉, 데이터는 복사되지 않고 뷰에 대한 변경은 원본이 바뀐다.

ndarray 슬라이스의 복사본을 얻고 싶다면 arr[5:8].copy()를 사용해서 명시적으로 복사해야 한다.

NumPy를 처음 접했거나 특히 데이터 복사가 자주 일어나는 다른 배열 프로그래밍 언어와 달리

데이터가 복사되지 않는다는 점의 이유는 대용량 데이터 처리를 염두해 설계되었기 때문이다.

2차원 배열에서 각 색인에 해당하는 요소는 스칼라 값이 아니라 1차원 배열이 된다.

In [109]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [110]:
arr2d[0][2]

3

In [111]:
arr2d[0, 2]

3

In [127]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [128]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [132]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

파이썬의 슬라이스 색인을 할 수 있다.

In [137]:
arr2d[2:, :]

array([[7, 8, 9]])

In [138]:
arr3d[1, :, :]

array([[10, 20, 30],
       [40, 50, 60]])

#### 4.1.5 boolean 색인

In [ ]:
중복된 이름이 포함된 배열에서

In [139]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [149]:
data = np.random.randn(7, 4)
data

array([[ 0.0242757 ,  0.06150383, -0.35716962, -1.39056276],
       [-1.30239224,  0.75708525,  1.3935878 , -0.0399094 ],
       [-0.6445266 ,  0.32517805, -0.54370376,  0.75612497],
       [-0.25717303, -0.39172315, -0.53521725, -1.1766891 ],
       [-1.13422605, -0.31023518, -0.28922263, -0.03010074],
       [ 1.08575954, -0.09504167,  0.35640325, -0.11413817],
       [-0.99529326,  0.68817251,  0.8955332 , -1.9423442 ]])

In [150]:
names == 'Bob'  # True는 0과 3

array([ True, False, False,  True, False, False, False])

In [155]:
data[names == 'Bob']  # data[0], data[3] 같음

array([[ 0.0242757 ,  0.06150383, -0.35716962, -1.39056276],
       [-0.25717303, -0.39172315, -0.53521725, -1.1766891 ]])

In [158]:
print(data[0], data[3])

[ 0.0242757   0.06150383 -0.35716962 -1.39056276] [-0.25717303 -0.39172315 -0.53521725 -1.1766891 ]


In [159]:
data[names == 'Bob', 2:]  # data[0과 3, 2:]

array([[-0.35716962, -1.39056276],
       [-0.53521725, -1.1766891 ]])

반대로 'Bob'이 아닌 요소를 선택하려면 != 연산자를 사용한다.

In [160]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [161]:
data[names != 'Bob']

array([[-1.30239224,  0.75708525,  1.3935878 , -0.0399094 ],
       [-0.6445266 ,  0.32517805, -0.54370376,  0.75612497],
       [-1.13422605, -0.31023518, -0.28922263, -0.03010074],
       [ 1.08575954, -0.09504167,  0.35640325, -0.11413817],
       [-0.99529326,  0.68817251,  0.8955332 , -1.9423442 ]])

또는 ~를 사용해서 조건절을 부정하면 된다.

In [165]:
data[~(names == 'Bob')]

array([[-1.30239224,  0.75708525,  1.3935878 , -0.0399094 ],
       [-0.6445266 ,  0.32517805, -0.54370376,  0.75612497],
       [-1.13422605, -0.31023518, -0.28922263, -0.03010074],
       [ 1.08575954, -0.09504167,  0.35640325, -0.11413817],
       [-0.99529326,  0.68817251,  0.8955332 , -1.9423442 ]])

&(and), |(or), 논리연산자, 대소비교 등으로도 색인할 수 있다.

In [167]:
data[data<0] = 0
data

array([[0.0242757 , 0.06150383, 0.        , 0.        ],
       [0.        , 0.75708525, 1.3935878 , 0.        ],
       [0.        , 0.32517805, 0.        , 0.75612497],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.08575954, 0.        , 0.35640325, 0.        ],
       [0.        , 0.68817251, 0.8955332 , 0.        ]])

In [169]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.75708525, 1.3935878 , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.08575954, 0.        , 0.35640325, 0.        ],
       [0.        , 0.68817251, 0.8955332 , 0.        ]])

#### 4.1.6 팬시색인

팬시 색인은 정부 배열을 사용해 색인 하는 방법이다.

In [173]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

arr의 4번째 6번째 0번째를 순서대로 부르고 싶다면

In [174]:
arr[[4, 6, 0]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.]])

이렇게 하면 된다.

뒤에서 1번째 5번째 4번째를 부르고 싶다면

In [175]:
arr[[-1, -5, -4]]

array([[7., 7., 7., 7.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

이렇게 하면 된다.

In [178]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

arr의 1, 5, 7, 2 행을 부르고 열들을 0, 3, 1, 2로 수정해보자

In [181]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [187]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

참고로 다음은 (0, 1), (5, 3), (7, 2), (2, 2)를 부른 것과 같다.

In [192]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

np.ix_ 함수를 사용하면 위에 참고처럼 해서 쉽게 색인 할 수 있다.

In [193]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 4.1.7 배열 전치와 축 바꾸기

배열 전치는 데이터를 복사하지 않고 데이터 모양이 바뀐 뷰를 반환하는 기능이다.

In [195]:
arr = np.arange(15).reshape((3, 5))

In [196]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [199]:
arr.T  # view만 바뀌고 원본은 바뀌지 않는다.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [200]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [201]:
arr = np.random.randn(6, 3)
arr

array([[ 1.59917919, -0.94574502, -0.34434032],
       [ 0.56960788,  0.13946796, -1.04309382],
       [ 0.305963  ,  0.32395953, -1.14748799],
       [-1.53141774,  0.70222944,  0.32491624],
       [ 0.1500174 ,  1.54050774, -1.97416857],
       [-0.67580147, -0.74574099, -1.02951522]])

행렬의 내적값을 구할 때 np.dot을 사용해 구할 수 있다.

In [202]:
np.dot(arr.T, arr)

array([[ 5.7998937 , -1.67418487, -1.59389943],
       [-1.67418487,  4.44125465, -2.23686419],
       [-1.59389943, -2.23686419,  7.58615735]])

In [212]:
arr = np.arange(24).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

다차원 배열의 경우 transpose 메소드는 튜플로 축 번호를 받아서 치환한다.

In [216]:
arr.transpose((1, 2, 0))  # (0, 1, 2)축의 순서(2x3x4)가 (1, 2, 0)순서(3x4x2)가 된다.

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

.T 속성을 이용하는 간단한 전치는 축을 뒤바꾸는 특별한 경우다.

ndarray에는 swapaxes 메소드가 있는데 2개의 축 번호를 받아서 배열을 뒤바꾼다.

항상 2개의 축만 바꾼다.

In [222]:
arr.swapaxes(2, 1)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])